
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex flex-col justify-center items-center">
          <h1>Social Media</h1>
          <nav className=" flex gap-40 text-lg justify-around items-center" >
            <Link className=" hover:bg-neutral-700 py-5 px-3 rounded-xl " href={"/"} >Home</Link>
            <Link className=" hover:bg-neutral-700 py-5 px-3 rounded-xl " href={"/about"} >About</Link>
            <Link className=" hover:bg-neutral-700 py-5 px-3 rounded-xl " href={"/posts"} >Posts</Link>
            <Link className=" hover:bg-neutral-700 py-5 px-3 rounded-xl " href={"/users"}>User</Link>
          </nav>
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
